#spring 配置
spring:
  datasource:
    url: "jdbc:mysql://my_server:3306/springbootdemo?useUnicode=true&\
                       characterEncoding=utf-8&allowMultiQueries=true&useSSL=false"
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-Main

  servlet:
    multipart:
      enabled: false
      max-file-size: 1MB
      max-request-size: 10MB
  boot:
    admin:
      client:
        url: http://172.16.1.22:6996/local-hbase

management:
  endpoints:
    web:
      exposure:
        include: '*'
  enpoint:
    health:
      show-details: always

server:
  port: 8866

logging:
  file: D:\MyProjects\allLog\springbootrbq\my11.log
  path: D:\MyProjects\allLog\springbootrbq

